#!/usr/bin/env python3
from __future__ import annotations

import argparse
import csv
import hashlib
import json
import re
import subprocess
import sys
import tempfile
from pathlib import Path


LEDGER_COLUMNS = (
    "as_of_date",
    "delivery_date",
    "carrier",
    "model_label",
    "git_commit",
    "config_hash",
    "carrier_metadata_sha256",
    "methodology_version",
    "prospective_or_backfill",
    "pipeline_status",
    "valid_day_status",
    "publication_time_ct",
    "manifest_sha256",
    "correction_of_manifest_sha256",
    "corrected_by_manifest_sha256",
    "advisory_detail_sha256",
    "advisory_csv_sha256",
    "positions_sha256",
    "scored_signals_sha256",
    "pipeline_log_sha256",
    "timestamp_status",
    "opentimestamps_proof_path",
    "exclusion_reason",
    "notes",
)

OUTCOME_SUMMARY_COLUMNS = (
    "as_of_date",
    "delivery_date",
    "carrier",
    "manifest_sha256",
    "methodology_version",
    "outcome_status",
    "rows_counted_sha256",
    "position_count",
    "priced_position_count",
    "missing_price_position_count",
    "total_mw",
    "filled_position_count",
    "filled_mw",
    "fill_rate",
    "hit_rate",
    "realized_filled_pnl",
    "realized_pnl_if_filled",
    "worst_path_hour_pnl",
    "expected_ev",
    "expected_filled_ev",
    "ercot_data_source",
    "ercot_data_product",
    "ercot_data_snapshot_sha256",
    "ercot_data_fetch_time_utc",
    "ercot_data_watermark",
    "private_outcome_sha256",
)

DAILY_LEDGER = Path("hashes/daily_manifest_hashes.csv")
BACKFILL_LEDGER = Path("hashes/backfill_manifest_hashes.csv")
TIMESTAMP_PROOFS = Path("hashes/timestamp_proofs.csv")
OUTCOME_SUMMARIES = Path("reports/audits/daily_outcome_summaries.csv")
CORRECTIONS_ROOT = Path("corrections")
ATTESTATION_ROOT = Path("attestations/private_manifest")
ATTESTATION_ALLOWED_SIGNERS = Path("attestations/allowed_signers")
ATTESTATION_SIGNATURE_NAMESPACE = "ercot-ptp-track-record-manifest-v1"

TIMESTAMP_PROOF_COLUMNS = (
    "as_of_date",
    "delivery_date",
    "carrier",
    "manifest_sha256",
    "public_ledger_row_sha256",
    "timestamp_status",
    "proof_input_path",
    "proof_input_sha256",
    "opentimestamps_proof_path",
    "opentimestamps_proof_sha256",
    "timestamped_at_utc",
    "notes",
)

FORBIDDEN_PATH_PATTERNS = (
    re.compile(r"(^|/)scored_signals_\d{4}-\d{2}-\d{2}\.(csv|json|parquet)$", re.IGNORECASE),
    re.compile(r"(^|/)positions_\d{4}-\d{2}-\d{2}\.(csv|json|parquet)$", re.IGNORECASE),
    re.compile(r"(^|/)book_delta_\d{4}-\d{2}-\d{2}\.(csv|json|parquet)$", re.IGNORECASE),
    re.compile(r"(^|/)advisory_detail_\d{4}-\d{2}-\d{2}\.(csv|json)$", re.IGNORECASE),
    re.compile(r"(^|/)advisory_debug_\d{4}-\d{2}-\d{2}\.(csv|json)$", re.IGNORECASE),
    re.compile(r"(^|/)w31_vs_w0(/|_|-|$)", re.IGNORECASE),
    re.compile(r"(^|/)private_audit(/|$)", re.IGNORECASE),
)

FORBIDDEN_CONTENT_PATTERNS = (
    re.compile(r"\bshadow_bid\b", re.IGNORECASE),
    re.compile(r"\bshadow_award_probability\b", re.IGNORECASE),
    re.compile(r"(^|[,{])\s*source\s*[:=]", re.IGNORECASE),
    re.compile(r"(^|[,{])\s*sink\s*[:=]", re.IGNORECASE),
    re.compile(r"(^|[,{])\s*mw\s*[:=]", re.IGNORECASE),
    re.compile(r"\bpair_id\s*,\s*hour_ending\b", re.IGNORECASE),
    re.compile(r"\bsource\s*,\s*sink\b", re.IGNORECASE),
    re.compile(r"\bsettlement_point\b", re.IGNORECASE),
)

CONTENT_SCAN_SUFFIXES = {".csv", ".json", ".md", ".txt", ".yml", ".yaml"}
CONTENT_SCAN_EXEMPT = {
    "scripts/verify_public_repo.py",
    "hashes/verification_guide.md",
}
ALLOWED_TIMESTAMP_STATUSES = {"timestamp_pending", "opentimestamps_proof", "timestamp_failed_giving_up"}
ALLOWED_OUTCOME_STATUSES = {"outcome_joined", "outcome_partial", "settlement_missing"}
GENERATED_HEADER = "Generated by ptp-trade track-record automation. Do not edit by hand."


def _read_csv_rows(path: Path, columns: tuple[str, ...]) -> tuple[list[dict[str, str]], list[str]]:
    if not path.is_file():
        return [], [f"missing csv: {path}"]
    with path.open("r", encoding="utf-8", newline="") as fh:
        reader = csv.DictReader(fh)
        if tuple(reader.fieldnames or ()) != columns:
            return [], [f"schema mismatch in {path}: {reader.fieldnames}"]
        return list(reader), []


def _sha256_json(payload: object) -> str:
    raw = json.dumps(payload, sort_keys=True, separators=(",", ":"), default=str).encode("utf-8")
    return hashlib.sha256(raw).hexdigest()


def _ledger_row_sha256(row: dict[str, str]) -> str:
    return _sha256_json({name: row.get(name, "") for name in LEDGER_COLUMNS})


def _correction_note_relpath(row: dict[str, str]) -> Path:
    manifest_sha = row.get("manifest_sha256") or "missing-manifest"
    return CORRECTIONS_ROOT / f"{row.get('as_of_date', 'unknown-date')}_{row.get('carrier', 'w31')}_{manifest_sha[:12]}.md"


def _verify_correction_note(root: Path, row: dict[str, str], *, line_number: int) -> list[str]:
    relpath = _correction_note_relpath(row)
    path = root / relpath
    if not path.is_file():
        return [f"daily ledger line {line_number} correction row missing public correction note: {relpath.as_posix()}"]
    text = path.read_text(encoding="utf-8")
    errors: list[str] = []
    if GENERATED_HEADER not in text:
        errors.append(f"correction note missing generated header: {relpath.as_posix()}")
    for label, value in (
        ("original manifest", row.get("correction_of_manifest_sha256", "")),
        ("correction manifest", row.get("manifest_sha256", "")),
    ):
        if value and value not in text:
            errors.append(f"correction note missing {label} sha: {relpath.as_posix()}")
    for required in ("## Cause", "## Blast Radius", "## Corrected Fields", "## Verification", "Responsible human approval:"):
        if required not in text:
            errors.append(f"correction note missing required section {required!r}: {relpath.as_posix()}")
    return errors


def _sha256_file(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as fh:
        for chunk in iter(lambda: fh.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def _read_base_csv_rows(
    root: Path,
    *,
    base_ref: str,
    relpath: Path,
    columns: tuple[str, ...],
) -> tuple[list[dict[str, str]], list[str]]:
    result = subprocess.run(
        ["git", "--no-optional-locks", "show", f"{base_ref}:{relpath.as_posix()}"],
        cwd=root,
        text=True,
        capture_output=True,
        check=False,
    )
    if result.returncode != 0:
        return [], []
    reader = csv.DictReader(result.stdout.splitlines())
    if tuple(reader.fieldnames or ()) != columns:
        return [], [f"base schema mismatch at {base_ref}:{relpath.as_posix()}: {reader.fieldnames}"]
    return list(reader), []


def _verify_append_only_csv(
    root: Path,
    *,
    relpath: Path,
    columns: tuple[str, ...],
    base_ref: str,
) -> list[str]:
    current_rows, current_errors = _read_csv_rows(root / relpath, columns)
    if current_errors:
        return current_errors
    base_rows, base_errors = _read_base_csv_rows(root, base_ref=base_ref, relpath=relpath, columns=columns)
    if base_errors:
        return base_errors
    if len(current_rows) < len(base_rows):
        return [f"{relpath.as_posix()} is not append-only: row count shrank {len(base_rows)} -> {len(current_rows)}"]
    for idx, prior in enumerate(base_rows):
        current = current_rows[idx]
        expected = {name: prior.get(name, "") for name in columns}
        actual = {name: current.get(name, "") for name in columns}
        if actual == expected:
            continue
        return [f"{relpath.as_posix()} is not append-only: prior row {idx + 2} was modified"]
    return []


def _verify_daily_ledger(root: Path, append_only_base_ref: str | None) -> tuple[list[dict[str, str]], list[str]]:
    rows, errors = _read_csv_rows(root / DAILY_LEDGER, LEDGER_COLUMNS)
    if append_only_base_ref:
        errors.extend(
            _verify_append_only_csv(
                root,
                relpath=DAILY_LEDGER,
                columns=LEDGER_COLUMNS,
                base_ref=append_only_base_ref,
            )
        )

    seen: set[tuple[str, str, str, str]] = set()
    prior_by_manifest: dict[str, dict[str, str]] = {}
    for idx, row in enumerate(rows, start=2):
        key = (row["as_of_date"], row["delivery_date"], row["carrier"], row["prospective_or_backfill"])
        correction_of = row["correction_of_manifest_sha256"]
        if correction_of:
            corrected = prior_by_manifest.get(correction_of)
            if corrected is None:
                errors.append(f"daily ledger line {idx} correction_of_manifest_sha256 does not reference an earlier row")
            else:
                corrected_key = (
                    corrected["as_of_date"],
                    corrected["delivery_date"],
                    corrected["carrier"],
                    corrected["prospective_or_backfill"],
                )
                if corrected_key != key:
                    errors.append(f"daily ledger line {idx} correction key does not match corrected row key")
            errors.extend(_verify_correction_note(root, row, line_number=idx))
        elif key in seen:
            errors.append(f"duplicate daily ledger key at line {idx}: {key}")
        else:
            seen.add(key)
        if row["carrier"] != "w31":
            errors.append(f"daily ledger line {idx} must use carrier=w31, got {row['carrier']!r}")
        if row["prospective_or_backfill"] != "prospective":
            errors.append(f"daily ledger line {idx} must be prospective-only")
        if not row["manifest_sha256"]:
            errors.append(f"daily ledger line {idx} missing manifest_sha256")
        if not row["methodology_version"]:
            errors.append(f"daily ledger line {idx} missing methodology_version")
        if row["valid_day_status"] == "excluded" and not row["exclusion_reason"]:
            errors.append(f"daily ledger line {idx} excluded without exclusion_reason")
        if row["timestamp_status"] not in ALLOWED_TIMESTAMP_STATUSES:
            errors.append(f"daily ledger line {idx} has unexpected timestamp_status={row['timestamp_status']!r}")
        proof_path = row["opentimestamps_proof_path"]
        if row["timestamp_status"] == "timestamp_pending" and proof_path:
            errors.append(f"daily ledger line {idx} pending timestamp row must not have proof path")
        if row["timestamp_status"] == "opentimestamps_proof":
            if not proof_path:
                errors.append(f"daily ledger line {idx} missing opentimestamps_proof_path")
            elif not proof_path.startswith("hashes/opentimestamps/"):
                errors.append(f"daily ledger line {idx} proof path must be under hashes/opentimestamps/")
        if row["timestamp_status"] == "timestamp_failed_giving_up" and proof_path:
            errors.append(f"daily ledger line {idx} failed timestamp row must not have proof path")
        if proof_path and not (root / proof_path).is_file():
            errors.append(f"daily ledger line {idx} proof path does not exist: {proof_path}")
        if row["manifest_sha256"]:
            prior_by_manifest[row["manifest_sha256"]] = row
    return rows, errors


def _verify_backfill_ledger(root: Path, append_only_base_ref: str | None) -> list[str]:
    rows, errors = _read_csv_rows(root / BACKFILL_LEDGER, LEDGER_COLUMNS)
    if append_only_base_ref:
        errors.extend(
            _verify_append_only_csv(
                root,
                relpath=BACKFILL_LEDGER,
                columns=LEDGER_COLUMNS,
                base_ref=append_only_base_ref,
            )
        )
    seen: set[tuple[str, str, str, str]] = set()
    for idx, row in enumerate(rows, start=2):
        key = (row["as_of_date"], row["delivery_date"], row["carrier"], row["prospective_or_backfill"])
        if key in seen:
            errors.append(f"duplicate backfill ledger key at line {idx}: {key}")
        seen.add(key)
        if row["carrier"] != "w31":
            errors.append(f"backfill ledger line {idx} must use carrier=w31, got {row['carrier']!r}")
        if row["prospective_or_backfill"] != "backfill":
            errors.append(f"backfill ledger line {idx} must be marked backfill")
    return errors


def _verify_outcome_summaries(
    root: Path,
    *,
    ledger_rows: list[dict[str, str]],
    append_only_base_ref: str | None,
) -> list[str]:
    path = root / OUTCOME_SUMMARIES
    if not path.exists():
        return []
    rows, errors = _read_csv_rows(path, OUTCOME_SUMMARY_COLUMNS)
    if append_only_base_ref:
        errors.extend(
            _verify_append_only_csv(
                root,
                relpath=OUTCOME_SUMMARIES,
                columns=OUTCOME_SUMMARY_COLUMNS,
                base_ref=append_only_base_ref,
            )
        )

    ledger_by_manifest = {row["manifest_sha256"]: row for row in ledger_rows if row.get("manifest_sha256")}
    seen: set[tuple[str, str, str, str]] = set()
    for idx, row in enumerate(rows, start=2):
        key = (row["as_of_date"], row["delivery_date"], row["carrier"], row["manifest_sha256"])
        if key in seen:
            errors.append(f"duplicate outcome summary key at line {idx}: {key}")
        seen.add(key)
        if row["carrier"] != "w31":
            errors.append(f"outcome summary line {idx} must use carrier=w31, got {row['carrier']!r}")
        if row["outcome_status"] not in ALLOWED_OUTCOME_STATUSES:
            errors.append(f"outcome summary line {idx} has unexpected outcome_status={row['outcome_status']!r}")
        if not row["methodology_version"]:
            errors.append(f"outcome summary line {idx} missing methodology_version")
        if not row["rows_counted_sha256"]:
            errors.append(f"outcome summary line {idx} missing rows_counted_sha256")
        if not row["private_outcome_sha256"]:
            errors.append(f"outcome summary line {idx} missing private_outcome_sha256")
        if row["outcome_status"] in {"outcome_joined", "outcome_partial"} and not row["ercot_data_snapshot_sha256"]:
            errors.append(f"outcome summary line {idx} missing ercot_data_snapshot_sha256")
        ledger_row = ledger_by_manifest.get(row["manifest_sha256"])
        if ledger_row is None:
            errors.append(f"outcome summary line {idx} does not reference a public ledger manifest")
        elif (
            ledger_row["as_of_date"] != row["as_of_date"]
            or ledger_row["delivery_date"] != row["delivery_date"]
            or ledger_row["carrier"] != row["carrier"]
            or ledger_row["methodology_version"] != row["methodology_version"]
        ):
            errors.append(f"outcome summary line {idx} does not match referenced ledger row")
    return errors


def _verify_timestamp_proofs(
    root: Path,
    *,
    ledger_rows: list[dict[str, str]],
    append_only_base_ref: str | None,
) -> list[str]:
    path = root / TIMESTAMP_PROOFS
    errors: list[str] = []
    if not path.exists():
        if any(row.get("timestamp_status") == "opentimestamps_proof" for row in ledger_rows):
            errors.append(f"missing timestamp proof ledger: {TIMESTAMP_PROOFS.as_posix()}")
        return errors
    rows, row_errors = _read_csv_rows(path, TIMESTAMP_PROOF_COLUMNS)
    errors.extend(row_errors)
    if row_errors:
        return errors
    if append_only_base_ref:
        errors.extend(
            _verify_append_only_csv(
                root,
                relpath=TIMESTAMP_PROOFS,
                columns=TIMESTAMP_PROOF_COLUMNS,
                base_ref=append_only_base_ref,
            )
        )
    ledger_by_manifest = {row["manifest_sha256"]: row for row in ledger_rows if row.get("manifest_sha256")}
    seen: set[str] = set()
    proof_by_manifest: dict[str, dict[str, str]] = {}
    for idx, row in enumerate(rows, start=2):
        manifest_sha = row["manifest_sha256"]
        if manifest_sha in seen:
            errors.append(f"duplicate timestamp proof row at line {idx}: {manifest_sha}")
        seen.add(manifest_sha)
        proof_by_manifest[manifest_sha] = row
        ledger_row = ledger_by_manifest.get(manifest_sha)
        if ledger_row is None:
            errors.append(f"timestamp proof line {idx} does not reference a public ledger manifest")
            continue
        if (
            ledger_row["as_of_date"] != row["as_of_date"]
            or ledger_row["delivery_date"] != row["delivery_date"]
            or ledger_row["carrier"] != row["carrier"]
        ):
            errors.append(f"timestamp proof line {idx} does not match referenced ledger row")
        if row["public_ledger_row_sha256"] != _ledger_row_sha256(ledger_row):
            errors.append(f"timestamp proof line {idx} has wrong public_ledger_row_sha256")
        if row["timestamp_status"] != "opentimestamps_proof":
            errors.append(f"timestamp proof line {idx} has unexpected timestamp_status={row['timestamp_status']!r}")
        proof_input_path = row["proof_input_path"]
        proof_path = row["opentimestamps_proof_path"]
        if not proof_input_path.startswith("hashes/opentimestamps/"):
            errors.append(f"timestamp proof line {idx} proof_input_path must be under hashes/opentimestamps/")
        if not proof_path.startswith("hashes/opentimestamps/"):
            errors.append(f"timestamp proof line {idx} opentimestamps_proof_path must be under hashes/opentimestamps/")
        for column, digest_column in (
            ("proof_input_path", "proof_input_sha256"),
            ("opentimestamps_proof_path", "opentimestamps_proof_sha256"),
        ):
            relpath = row[column]
            artifact = root / relpath
            if not artifact.is_file():
                errors.append(f"timestamp proof line {idx} missing artifact: {relpath}")
                continue
            if row[digest_column] != _sha256_file(artifact):
                errors.append(f"timestamp proof line {idx} {digest_column} does not match artifact")
    for idx, ledger_row in enumerate(ledger_rows, start=2):
        if ledger_row.get("timestamp_status") != "opentimestamps_proof":
            continue
        proof_row = proof_by_manifest.get(ledger_row["manifest_sha256"])
        if proof_row is None:
            errors.append(f"daily ledger line {idx} has proof status but no timestamp proof row")
        elif proof_row["opentimestamps_proof_path"] != ledger_row["opentimestamps_proof_path"]:
            errors.append(f"daily ledger line {idx} proof path does not match timestamp proof row")
    return errors


def _canonical_attestation_body(payload: dict[str, object]) -> bytes:
    return json.dumps(payload, sort_keys=True, separators=(",", ":"), default=str).encode("utf-8")


def _allowed_signer_identity_present(path: Path, identity: str) -> bool:
    try:
        lines = path.read_text(encoding="utf-8").splitlines()
    except FileNotFoundError:
        return False
    for raw_line in lines:
        line = raw_line.strip()
        if not line or line.startswith("#"):
            continue
        principals = line.split(None, 1)[0]
        if identity in {principal.strip() for principal in principals.split(",")}:
            return True
    return False


def _verify_ssh_attestation_signature(payload: dict[str, object], *, allowed_signers_path: Path) -> str | None:
    signature = payload.get("signature")
    public_key = str(payload.get("public_key") or "")
    identity = str(payload.get("signature_identity") or "")
    namespace = str(payload.get("signature_namespace") or "")
    if not signature or not public_key or not identity or not namespace:
        return "missing signature, public_key, signature_identity, or signature_namespace"
    if not allowed_signers_path.is_file():
        return f"allowed signers file missing: {ATTESTATION_ALLOWED_SIGNERS.as_posix()}"
    if not _allowed_signer_identity_present(allowed_signers_path, identity):
        return f"signature_identity {identity!r} is not listed in {ATTESTATION_ALLOWED_SIGNERS.as_posix()}"
    signed_payload = dict(payload)
    signed_payload.pop("signature", None)
    body = _canonical_attestation_body(signed_payload)
    with tempfile.TemporaryDirectory(prefix="track-record-attestation-verify-") as tmp_raw:
        root = Path(tmp_raw)
        signature_path = root / "attestation.sig"
        signature_path.write_text(str(signature), encoding="utf-8")
        result = subprocess.run(
            [
                "ssh-keygen",
                "-Y",
                "verify",
                "-f",
                str(allowed_signers_path),
                "-I",
                identity,
                "-n",
                namespace,
                "-s",
                str(signature_path),
            ],
            input=body,
            capture_output=True,
            check=False,
        )
    if result.returncode != 0:
        return (result.stderr or result.stdout).decode("utf-8", errors="replace").strip() or "signature verification failed"
    return None


def _verify_attestations(root: Path, ledger_rows: list[dict[str, str]]) -> list[str]:
    errors: list[str] = []
    attestation_root = root / ATTESTATION_ROOT
    if not attestation_root.exists():
        return errors
    allowed_signers_path = root / ATTESTATION_ALLOWED_SIGNERS
    ledger_by_manifest = {row["manifest_sha256"]: row for row in ledger_rows if row.get("manifest_sha256")}
    for path in sorted(attestation_root.rglob("*.json")):
        rel = path.relative_to(root).as_posix()
        try:
            payload = json.loads(path.read_text(encoding="utf-8"))
        except json.JSONDecodeError as exc:
            errors.append(f"invalid attestation json in {rel}: {exc}")
            continue
        if not isinstance(payload, dict):
            errors.append(f"attestation is not an object: {rel}")
            continue
        if payload.get("signature_algorithm") != "openssh-signature-v1":
            errors.append(f"attestation has unsupported signature_algorithm in {rel}")
        if payload.get("signature_namespace") != ATTESTATION_SIGNATURE_NAMESPACE:
            errors.append(f"attestation has unexpected signature_namespace in {rel}")
        manifest_sha256 = str(payload.get("manifest_sha256") or "")
        ledger_row = ledger_by_manifest.get(manifest_sha256)
        if ledger_row is None:
            errors.append(f"attestation does not reference a public ledger manifest: {rel}")
        else:
            expected_row_sha = _ledger_row_sha256(ledger_row)
            if payload.get("public_ledger_row_sha256") != expected_row_sha:
                errors.append(f"attestation ledger row hash mismatch in {rel}")
        signature_error = _verify_ssh_attestation_signature(payload, allowed_signers_path=allowed_signers_path)
        if signature_error:
            errors.append(f"attestation signature verification failed in {rel}: {signature_error}")
    return errors


def _verify_reports(root: Path) -> list[str]:
    errors: list[str] = []
    for report_root in (root / "reports" / "weekly", root / "reports" / "monthly"):
        if not report_root.exists():
            continue
        for markdown_path in report_root.glob("*.md"):
            if markdown_path.name == "README.md":
                continue
            rel = markdown_path.relative_to(root).as_posix()
            text = markdown_path.read_text(encoding="utf-8")
            if GENERATED_HEADER not in text:
                errors.append(f"report missing generated header: {rel}")
            if "Rows counted SHA256:" not in text:
                errors.append(f"report missing rows_counted_sha256: {rel}")
            if "Methodology versions:" not in text:
                errors.append(f"report missing methodology versions: {rel}")
            if "## Operational Discipline" not in text:
                errors.append(f"report missing operational discipline section: {rel}")
            if "## Risk/Distribution" not in text:
                errors.append(f"report missing risk/distribution section: {rel}")
            if not markdown_path.with_suffix(".csv").is_file():
                errors.append(f"report missing companion csv: {markdown_path.with_suffix('.csv').relative_to(root).as_posix()}")
    return errors


def _verify_status_docs(root: Path) -> list[str]:
    errors: list[str] = []
    for relpath in ("README.md", "carrier/current.md", "carrier/operational_log.md"):
        path = root / relpath
        if not path.is_file():
            errors.append(f"missing generated public status doc: {relpath}")
            continue
        if GENERATED_HEADER not in path.read_text(encoding="utf-8"):
            errors.append(f"public status doc missing generated header: {relpath}")
    return errors


def _verify_privacy_boundary(root: Path) -> list[str]:
    errors: list[str] = []
    for path in root.rglob("*"):
        if not path.is_file() or ".git" in path.parts:
            continue
        rel = path.relative_to(root).as_posix()
        lowered = rel.lower()
        for pattern in FORBIDDEN_PATH_PATTERNS:
            if pattern.search(lowered):
                errors.append(f"forbidden public artifact path: {rel}")
                break
        if rel in CONTENT_SCAN_EXEMPT or path.suffix.lower() not in CONTENT_SCAN_SUFFIXES:
            continue
        try:
            text = path.read_text(encoding="utf-8")
        except UnicodeDecodeError:
            continue
        for pattern in FORBIDDEN_CONTENT_PATTERNS:
            if pattern.search(text):
                errors.append(f"forbidden raw-signal content pattern {pattern.pattern!r} in {rel}")
                break
    return errors


def verify(root: Path, *, append_only_base_ref: str | None = None) -> list[str]:
    errors: list[str] = []
    ledger_rows, ledger_errors = _verify_daily_ledger(root, append_only_base_ref)
    errors.extend(ledger_errors)
    errors.extend(_verify_backfill_ledger(root, append_only_base_ref))
    errors.extend(_verify_outcome_summaries(root, ledger_rows=ledger_rows, append_only_base_ref=append_only_base_ref))
    errors.extend(_verify_timestamp_proofs(root, ledger_rows=ledger_rows, append_only_base_ref=append_only_base_ref))
    errors.extend(_verify_attestations(root, ledger_rows))
    errors.extend(_verify_reports(root))
    errors.extend(_verify_status_docs(root))
    errors.extend(_verify_privacy_boundary(root))
    return errors


def main() -> int:
    parser = argparse.ArgumentParser(description="Verify public ERCOT PTP track-record repo guardrails.")
    parser.add_argument("root", nargs="?", default=".")
    parser.add_argument(
        "--append-only-base-ref",
        default=None,
        help="Optional git ref whose public CSV rows must remain an exact prefix of current rows.",
    )
    args = parser.parse_args()
    errors = verify(Path(args.root).resolve(), append_only_base_ref=args.append_only_base_ref)
    if errors:
        for error in errors:
            print(f"ERROR: {error}", file=sys.stderr)
        return 1
    print("VERIFY_OK public_track_record")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
