#!/usr/bin/env python3
from __future__ import annotations

import argparse
import csv
import hashlib
import json
import math
import re
import subprocess
import sys
import tempfile
from datetime import date, timedelta
from pathlib import Path


LEDGER_COLUMNS = (
    "as_of_date",
    "delivery_date",
    "carrier",
    "model_label",
    "git_commit",
    "config_hash",
    "carrier_metadata_sha256",
    "methodology_version",
    "prospective_or_backfill",
    "pipeline_status",
    "valid_day_status",
    "publication_time_ct",
    "manifest_sha256",
    "correction_of_manifest_sha256",
    "corrected_by_manifest_sha256",
    "advisory_detail_sha256",
    "advisory_csv_sha256",
    "positions_sha256",
    "scored_signals_sha256",
    "pipeline_log_sha256",
    "timestamp_status",
    "opentimestamps_proof_path",
    "exclusion_reason",
    "notes",
)

OUTCOME_SUMMARY_COLUMNS = (
    "as_of_date",
    "delivery_date",
    "carrier",
    "manifest_sha256",
    "methodology_version",
    "outcome_methodology_version",
    "outcome_status",
    "rows_counted_sha256",
    "position_count",
    "priced_position_count",
    "missing_price_position_count",
    "total_mw",
    "filled_position_count",
    "filled_mw",
    "fill_rate",
    "hit_rate",
    "realized_filled_pnl",
    "realized_pnl_if_filled",
    "worst_path_hour_pnl",
    "expected_ev",
    "expected_filled_ev",
    "ercot_data_source",
    "ercot_data_product",
    "ercot_data_snapshot_sha256",
    "ercot_data_fetch_time_utc",
    "ercot_data_watermark",
    "private_outcome_sha256",
)

DAILY_LEDGER = Path("hashes/daily_manifest_hashes.csv")
BACKFILL_LEDGER = Path("hashes/backfill_manifest_hashes.csv")
TIMESTAMP_PROOFS = Path("hashes/timestamp_proofs.csv")
OUTCOME_SUMMARIES = Path("reports/audits/daily_outcome_summaries.csv")
CORRECTIONS_ROOT = Path("corrections")
ATTESTATION_ROOT = Path("attestations/private_manifest")
ATTESTATION_ALLOWED_SIGNERS = Path("attestations/allowed_signers")
ATTESTATION_SIGNATURE_NAMESPACE = "ercot-ptp-track-record-manifest-v1"
PUBLIC_SAMPLE_ROOT = Path("samples/delayed_advisory_examples")

TIMESTAMP_PROOF_COLUMNS = (
    "as_of_date",
    "delivery_date",
    "carrier",
    "manifest_sha256",
    "public_ledger_row_sha256",
    "timestamp_status",
    "proof_input_path",
    "proof_input_sha256",
    "opentimestamps_proof_path",
    "opentimestamps_proof_sha256",
    "timestamped_at_utc",
    "notes",
)

FORBIDDEN_PATH_PATTERNS = (
    re.compile(r"(^|/)scored_signals_\d{4}-\d{2}-\d{2}\.(csv|json|parquet)$", re.IGNORECASE),
    re.compile(r"(^|/)positions_\d{4}-\d{2}-\d{2}\.(csv|json|parquet)$", re.IGNORECASE),
    re.compile(r"(^|/)book_delta_\d{4}-\d{2}-\d{2}\.(csv|json|parquet)$", re.IGNORECASE),
    re.compile(r"(^|/)advisory_detail_\d{4}-\d{2}-\d{2}\.(csv|json)$", re.IGNORECASE),
    re.compile(r"(^|/)advisory_debug_\d{4}-\d{2}-\d{2}\.(csv|json)$", re.IGNORECASE),
    re.compile(r"(^|/)w31_vs_w0(/|_|-|$)", re.IGNORECASE),
    re.compile(r"(^|/)private_audit(/|$)", re.IGNORECASE),
)

FORBIDDEN_CONTENT_PATTERNS = (
    re.compile(r"\bshadow_bid\b", re.IGNORECASE),
    re.compile(r"\bshadow_award_probability\b", re.IGNORECASE),
    re.compile(r"(^|[,{])\s*source\s*[:=]", re.IGNORECASE),
    re.compile(r"(^|[,{])\s*sink\s*[:=]", re.IGNORECASE),
    re.compile(r"(^|[,{])\s*mw\s*[:=]", re.IGNORECASE),
    re.compile(r'["\']source["\']\s*:', re.IGNORECASE),
    re.compile(r'["\']sink["\']\s*:', re.IGNORECASE),
    re.compile(r'["\']mw["\']\s*:', re.IGNORECASE),
    re.compile(r"\bpair_id\s*,\s*hour_ending\b", re.IGNORECASE),
    re.compile(r"\bsource\s*,\s*sink\b", re.IGNORECASE),
    re.compile(r"\|\s*source\s*\|\s*sink\s*\|", re.IGNORECASE),
    re.compile(r"\bsettlement_point\b", re.IGNORECASE),
)

OPERATIONAL_LOG_FORBIDDEN_CONTENT_PATTERNS = (
    *FORBIDDEN_CONTENT_PATTERNS,
    re.compile(r"(^|/)\.?(?:env|ssh)(/|$)", re.IGNORECASE),
    re.compile(r"(^|/)(?:home|root|tmp|var|mnt)/", re.IGNORECASE),
    re.compile(r"\b(?:private_audit|private_vault|private-vault|ptp-track-record)\b", re.IGNORECASE),
    re.compile(r"\b(?:secret|token|password|credential|webhook)\b", re.IGNORECASE),
    re.compile(r"\b(?:AWS|GITHUB|OPENAI|TRACK_RECORD_ALERT_WEBHOOK_URL)_", re.IGNORECASE),
    re.compile(r"\b(?:advisory_detail|advisory_debug|scored_signals|positions|book_delta)_\d{4}-\d{2}-\d{2}\b", re.IGNORECASE),
    re.compile(r"\bw0\b", re.IGNORECASE),
    re.compile(r"\bw31_vs_w0\b", re.IGNORECASE),
)

CONTENT_SCAN_SUFFIXES = {".csv", ".json", ".md", ".txt", ".yml", ".yaml"}
CONTENT_SCAN_EXEMPT = {
    "scripts/verify_public_repo.py",
    "hashes/verification_guide.md",
}
ALLOWED_TIMESTAMP_STATUSES = {"timestamp_pending", "opentimestamps_proof", "timestamp_failed_giving_up"}
PUBLIC_OUTCOME_STATUS = "outcome_joined"
GENERATED_HEADER = "Generated by ptp-trade track-record automation. Do not edit by hand."
DEFAULT_METHODOLOGY_VERSION = "m2026.05.26.v1"
TRACK_RECORD_COMMIT_PREFIX = "track-record:"
LEGACY_AUDIT_COMMIT_MESSAGE_EXEMPTIONS = frozenset(
    {
        # Signed operational-log note from the initial direct-push transition.
        "82b35f8a36bd154de2c00352df5b5e40722f7306",
    }
)
GENERATED_AUDIT_COMMIT_PATH_PREFIXES = (
    "README.md",
    "hashes/",
    "attestations/",
    "carrier/",
    "reports/",
    "corrections/",
    "samples/",
    "releases/",
)


def _read_csv_rows(path: Path, columns: tuple[str, ...]) -> tuple[list[dict[str, str]], list[str]]:
    if not path.is_file():
        return [], [f"missing csv: {path}"]
    with path.open("r", encoding="utf-8", newline="") as fh:
        reader = csv.DictReader(fh)
        if tuple(reader.fieldnames or ()) != columns:
            return [], [f"schema mismatch in {path}: {reader.fieldnames}"]
        return list(reader), []


def _sha256_json(payload: object) -> str:
    raw = json.dumps(payload, sort_keys=True, separators=(",", ":"), default=str).encode("utf-8")
    return hashlib.sha256(raw).hexdigest()


def _ledger_row_sha256(row: dict[str, str]) -> str:
    return _sha256_json({name: row.get(name, "") for name in LEDGER_COLUMNS})


def _timestamp_proof_input_relpath(row: dict[str, str]) -> str:
    as_of = row.get("as_of_date", "")
    carrier = row.get("carrier", "")
    manifest_sha = row.get("manifest_sha256", "")
    if not as_of or not carrier or not manifest_sha:
        return ""
    year, month, _day = as_of.split("-", 2)
    return f"hashes/opentimestamps/{year}/{month}/{as_of}_{carrier}_{manifest_sha}"


def _timestamp_proof_input_payload(row: dict[str, str]) -> str:
    return "\n".join(
        [
            "ercot_ptp_track_record_timestamp_v0",
            f"as_of_date={row.get('as_of_date', '')}",
            f"delivery_date={row.get('delivery_date', '')}",
            f"carrier={row.get('carrier', '')}",
            f"manifest_sha256={row.get('manifest_sha256', '')}",
            "",
        ]
    )


def _git_check_output(repo: Path, args: list[str]) -> tuple[str, str]:
    result = subprocess.run(
        ["git", "--no-optional-locks", *args],
        cwd=repo,
        text=True,
        capture_output=True,
        check=False,
    )
    return result.stdout.strip(), result.stderr.strip()


def _is_git_repo(repo: Path) -> bool:
    stdout, _stderr = _git_check_output(repo, ["rev-parse", "--is-inside-work-tree"])
    return stdout == "true"


def _audit_artifact_commit_touched(paths: list[str]) -> bool:
    for path in paths:
        if path == "README.md":
            return True
        if any(path.startswith(prefix) for prefix in GENERATED_AUDIT_COMMIT_PATH_PREFIXES if prefix != "README.md"):
            return True
    return False


def _commit_signature_status(root: Path, commit_sha: str) -> str:
    stdout, _stderr = _git_check_output(root, ["log", "-1", "--format=%G?", commit_sha])
    return stdout.strip() or "N"


def _verify_track_record_audit_commits(
    root: Path,
    *,
    base_ref: str | None,
    require_signed: bool,
) -> list[str]:
    if not _is_git_repo(root):
        return []
    head_stdout, head_stderr = _git_check_output(root, ["rev-parse", "--verify", "HEAD"])
    if head_stderr and not head_stdout:
        return []
    rev = "HEAD" if not base_ref else f"{base_ref}..HEAD"
    stdout, stderr = _git_check_output(root, ["log", "--format=%H%x1f%s", rev])
    if stderr and not stdout:
        return [f"could not inspect public repo commits: {stderr}"]
    errors: list[str] = []
    for line in stdout.splitlines():
        if not line:
            continue
        try:
            commit_sha, subject = line.split("\x1f", 1)
        except ValueError:
            continue
        files_stdout, files_stderr = _git_check_output(root, ["show", "--format=", "--name-only", commit_sha])
        if files_stderr and not files_stdout:
            errors.append(f"could not inspect changed files for commit {commit_sha[:12]}: {files_stderr}")
            continue
        changed_paths = [path for path in files_stdout.splitlines() if path]
        if not _audit_artifact_commit_touched(changed_paths):
            continue
        if not subject.startswith(TRACK_RECORD_COMMIT_PREFIX) and commit_sha not in LEGACY_AUDIT_COMMIT_MESSAGE_EXEMPTIONS:
            errors.append(f"audit artifact commit {commit_sha[:12]} must use '{TRACK_RECORD_COMMIT_PREFIX}' prefix: {subject!r}")
        if require_signed:
            signature_status = _commit_signature_status(root, commit_sha)
            if signature_status not in {"G", "U", "X", "Y"}:
                errors.append(f"audit artifact commit {commit_sha[:12]} must be signed; git signature status={signature_status!r}")
    return errors


def _report_rows_counted_sha256(rows: list[dict[str, str]]) -> str:
    selected = [
        {
            "as_of_date": row.get("as_of_date", ""),
            "delivery_date": row.get("delivery_date", ""),
            "carrier": row.get("carrier", ""),
            "manifest_sha256": row.get("manifest_sha256", ""),
            "rows_counted_sha256": row.get("rows_counted_sha256", ""),
            "private_outcome_sha256": row.get("private_outcome_sha256", ""),
        }
        for row in rows
    ]
    return _sha256_json(sorted(selected, key=lambda row: (row["delivery_date"], row["manifest_sha256"])))


def _to_float(row: dict[str, str], column: str) -> float:
    try:
        return float(row.get(column, "") or 0.0)
    except ValueError:
        return 0.0


def _finite_metric(value: float | int | None) -> float | str:
    if value is None:
        return ""
    value = float(value)
    if not math.isfinite(value):
        return ""
    return round(value, 6)


def _sample_std(values: list[float]) -> float:
    if len(values) <= 1:
        return math.nan
    mean = sum(values) / len(values)
    variance = sum((value - mean) ** 2 for value in values) / (len(values) - 1)
    return math.sqrt(variance)


def _median(values: list[float]) -> float:
    ordered = sorted(values)
    midpoint = len(ordered) // 2
    if len(ordered) % 2:
        return ordered[midpoint]
    return (ordered[midpoint - 1] + ordered[midpoint]) / 2


def _methodology_versions(rows: list[dict[str, str]]) -> list[str]:
    return sorted({row.get("methodology_version", "") for row in rows if row.get("methodology_version", "")})


def _methodology_segments(rows: list[dict[str, str]]) -> list[dict[str, object]]:
    segments: list[dict[str, object]] = []
    for version in _methodology_versions(rows):
        group = [row for row in rows if row.get("methodology_version", "") == version]
        if not group:
            continue
        delivery_dates = [row["delivery_date"] for row in group]
        segments.append(
            {
                "methodology_version": version,
                "days_counted": len(group),
                "position_count": int(sum(_to_float(row, "position_count") for row in group)),
                "filled_position_count": int(sum(_to_float(row, "filled_position_count") for row in group)),
                "realized_filled_pnl": round(sum(_to_float(row, "realized_filled_pnl") for row in group), 6),
                "expected_filled_ev": round(sum(_to_float(row, "expected_filled_ev") for row in group), 6),
                "start_delivery_date": min(delivery_dates),
                "end_delivery_date": max(delivery_dates),
            }
        )
    return segments


def _period_ledger_summary(
    root: Path,
    *,
    start_date: date,
    end_date: date,
    report_date: date,
    min_delay_days: int,
) -> dict[str, object]:
    rows, errors = _read_csv_rows(root / DAILY_LEDGER, LEDGER_COLUMNS)
    if errors:
        rows = []
    latest_allowed = report_date - timedelta(days=min_delay_days)
    period = [
        row
        for row in rows
        if row.get("carrier") == "w31"
        and row.get("prospective_or_backfill") == "prospective"
        and start_date <= date.fromisoformat(row["delivery_date"]) <= end_date
        and date.fromisoformat(row["delivery_date"]) <= latest_allowed
    ]
    if not period:
        return {
            "public_ledger_rows": 0,
            "valid_day_count": 0,
            "invalid_day_count": 0,
            "excluded_day_count": 0,
            "valid_day_rate": "",
            "unsettled_or_missing_valid_outcomes": 0,
        }
    valid = sum(1 for row in period if row.get("valid_day_status") == "valid")
    invalid = sum(1 for row in period if row.get("valid_day_status") == "invalid")
    excluded = sum(1 for row in period if row.get("valid_day_status") == "excluded")
    return {
        "public_ledger_rows": len(period),
        "valid_day_count": valid,
        "invalid_day_count": invalid,
        "excluded_day_count": excluded,
        "valid_day_rate": _finite_metric(valid / len(period) if period else None),
        "unsettled_or_missing_valid_outcomes": 0,
    }


def _track_record_valid_day_count(root: Path, *, report_date: date, min_delay_days: int) -> int:
    ledger_rows, ledger_errors = _read_csv_rows(root / DAILY_LEDGER, LEDGER_COLUMNS)
    outcome_rows, outcome_errors = _read_csv_rows(root / OUTCOME_SUMMARIES, OUTCOME_SUMMARY_COLUMNS)
    if ledger_errors or outcome_errors:
        return 0
    corrected = {row["correction_of_manifest_sha256"] for row in ledger_rows if row.get("correction_of_manifest_sha256")}
    ledger_by_key = {
        (row["as_of_date"], row["delivery_date"], row["carrier"], row["manifest_sha256"], row["methodology_version"]): row
        for row in ledger_rows
        if row.get("manifest_sha256") not in corrected
    }
    latest_allowed = report_date - timedelta(days=min_delay_days)
    keys: set[tuple[str, str, str]] = set()
    for row in outcome_rows:
        key = (row["as_of_date"], row["delivery_date"], row["carrier"], row["manifest_sha256"], row["methodology_version"])
        ledger = ledger_by_key.get(key)
        if ledger is None:
            continue
        if ledger.get("carrier") != "w31" or ledger.get("prospective_or_backfill") != "prospective":
            continue
        if ledger.get("valid_day_status") != "valid" or row.get("outcome_status") != "outcome_joined":
            continue
        if date.fromisoformat(row["delivery_date"]) <= latest_allowed:
            keys.add((row["as_of_date"], row["delivery_date"], row["manifest_sha256"]))
    return len(keys)


def _daily_distribution(rows: list[dict[str, str]]) -> dict[str, object]:
    daily: dict[str, float] = {}
    for row in rows:
        daily[row["delivery_date"]] = daily.get(row["delivery_date"], 0.0) + _to_float(row, "realized_filled_pnl")
    if not daily:
        return {
            "mean_daily_realized_filled_pnl": "",
            "median_daily_realized_filled_pnl": "",
            "daily_realized_filled_pnl_std": "",
            "best_day": "",
            "best_day_pnl": "",
            "worst_day": "",
            "worst_day_pnl": "",
            "max_drawdown": "",
            "annualized_sharpe": "",
            "annualized_sortino": "",
        }
    ordered = sorted(daily.items())
    values = [value for _day, value in ordered]
    cumulative = 0.0
    peak = -math.inf
    drawdowns: list[float] = []
    for value in values:
        cumulative += value
        peak = max(peak, cumulative)
        drawdowns.append(cumulative - peak)
    mean = sum(values) / len(values)
    std = _sample_std(values)
    downside = [value for value in values if value < 0]
    downside_std = _sample_std(downside) if len(downside) > 1 else math.nan
    sharpe = (mean / std) * math.sqrt(252) if len(values) > 1 and std and math.isfinite(std) else math.nan
    sortino = (
        (mean / downside_std) * math.sqrt(252)
        if len(downside) > 1 and downside_std and math.isfinite(downside_std)
        else math.nan
    )
    best_day, best_pnl = max(ordered, key=lambda item: item[1])
    worst_day, worst_pnl = min(ordered, key=lambda item: item[1])
    return {
        "mean_daily_realized_filled_pnl": _finite_metric(mean),
        "median_daily_realized_filled_pnl": _finite_metric(_median(values)),
        "daily_realized_filled_pnl_std": _finite_metric(std),
        "best_day": best_day,
        "best_day_pnl": _finite_metric(best_pnl),
        "worst_day": worst_day,
        "worst_day_pnl": _finite_metric(worst_pnl),
        "max_drawdown": _finite_metric(min(drawdowns)),
        "annualized_sharpe": _finite_metric(sharpe),
        "annualized_sortino": _finite_metric(sortino),
    }


def _report_summary(
    root: Path,
    *,
    kind: str,
    rows: list[dict[str, str]],
    start_date: date,
    end_date: date,
    report_date: date,
    min_delay_days: int,
) -> dict[str, object]:
    ledger_summary = _period_ledger_summary(
        root,
        start_date=start_date,
        end_date=end_date,
        report_date=report_date,
        min_delay_days=min_delay_days,
    )
    ledger_summary["unsettled_or_missing_valid_outcomes"] = max(int(ledger_summary["valid_day_count"]) - len(rows), 0)
    position_count = sum(_to_float(row, "position_count") for row in rows)
    filled_position_count = sum(_to_float(row, "filled_position_count") for row in rows)
    hit_values = [_to_float(row, "hit_rate") for row in rows if row.get("hit_rate", "") != ""]
    summary: dict[str, object] = {
        "kind": kind,
        "start_date": start_date.isoformat(),
        "end_date": end_date.isoformat(),
        "report_date": report_date.isoformat(),
        "rows_counted_sha256": _report_rows_counted_sha256(rows),
        "methodology_versions": _methodology_versions(rows),
        "methodology_segments": _methodology_segments(rows),
        "days_counted": len(rows),
        "track_record_valid_day_count": _track_record_valid_day_count(
            root,
            report_date=report_date,
            min_delay_days=min_delay_days,
        ),
        **ledger_summary,
        "total_positions": int(position_count),
        "total_mw": round(sum(_to_float(row, "total_mw") for row in rows), 6),
        "filled_positions": int(filled_position_count),
        "filled_mw": round(sum(_to_float(row, "filled_mw") for row in rows), 6),
        "fill_rate": round(filled_position_count / max(position_count, 1.0), 6),
        "hit_rate": round(sum(hit_values) / len(hit_values), 6) if hit_values else "",
        "realized_filled_pnl": round(sum(_to_float(row, "realized_filled_pnl") for row in rows), 6),
        "realized_pnl_if_filled": round(sum(_to_float(row, "realized_pnl_if_filled") for row in rows), 6),
        "worst_path_hour_pnl": round(min(_to_float(row, "worst_path_hour_pnl") for row in rows), 6),
        "expected_ev": round(sum(_to_float(row, "expected_ev") for row in rows), 6),
        "expected_filled_ev": round(sum(_to_float(row, "expected_filled_ev") for row in rows), 6),
        "manifest_count": len({row["manifest_sha256"] for row in rows}),
    }
    summary.update(_daily_distribution(rows))
    return summary


def _render_report_markdown(summary: dict[str, object], rows: list[dict[str, str]]) -> str:
    methodology_versions = ", ".join(f"`{version}`" for version in summary["methodology_versions"])
    lines = [
        GENERATED_HEADER,
        "",
        f"# ERCOT PTP {str(summary['kind']).title()} Track Record",
        "",
        f"Period: {summary['start_date']} to {summary['end_date']}",
        f"Report date: {summary['report_date']}",
        f"Methodology versions: {methodology_versions}",
        f"Rows counted SHA256: `{summary['rows_counted_sha256']}`",
        "",
        "## Summary",
        "",
        f"- Settlement-complete valid days counted: {summary['days_counted']}",
        f"- Realized filled PnL: {summary['realized_filled_pnl']}",
        f"- Fill rate: {summary['fill_rate']}",
        f"- Hit rate: {summary['hit_rate']}",
        f"- Worst path-hour PnL: {summary['worst_path_hour_pnl']}",
        f"- Expected filled EV: {summary['expected_filled_ev']}",
        "",
        "## Operational Discipline",
        "",
        f"- Public ledger rows in period: {summary['public_ledger_rows']}",
        f"- Valid days in ledger: {summary['valid_day_count']}",
        f"- Settlement-complete valid days in full track record: {summary['track_record_valid_day_count']}",
        f"- Invalid days in ledger: {summary['invalid_day_count']}",
        f"- Excluded days in ledger: {summary['excluded_day_count']}",
        f"- Valid-day rate: {summary['valid_day_rate']}",
        f"- Valid days without settled outcome in this report: {summary['unsettled_or_missing_valid_outcomes']}",
        "",
        "## Risk/Distribution",
        "",
        f"- Cumulative realized filled PnL: {summary['realized_filled_pnl']}",
        f"- Mean daily realized filled PnL: {summary['mean_daily_realized_filled_pnl']}",
        f"- Median daily realized filled PnL: {summary['median_daily_realized_filled_pnl']}",
        f"- Daily realized filled PnL std: {summary['daily_realized_filled_pnl_std']}",
        f"- Best day: {summary['best_day']} ({summary['best_day_pnl']})",
        f"- Worst day: {summary['worst_day']} ({summary['worst_day_pnl']})",
        f"- Max drawdown: {summary['max_drawdown']}",
        f"- Annualized Sharpe: {summary['annualized_sharpe']}",
        f"- Annualized Sortino: {summary['annualized_sortino']}",
        "",
    ]
    segments = summary["methodology_segments"]
    if isinstance(segments, list) and len(segments) > 1:
        lines.extend(
            [
                "## Methodology Segments",
                "",
                "| methodology_version | delivery_start | delivery_end | days | positions | filled_positions | realized_filled_pnl | expected_filled_ev |",
                "|---|---|---|---:|---:|---:|---:|---:|",
            ]
        )
        for segment in segments:
            lines.append(
                f"| `{segment['methodology_version']}` | {segment['start_delivery_date']} | {segment['end_delivery_date']} | "
                f"{segment['days_counted']} | {segment['position_count']} | {segment['filled_position_count']} | "
                f"{segment['realized_filled_pnl']} | {segment['expected_filled_ev']} |"
            )
        lines.append("")
    lines.extend(
        [
            "## Hash References",
            "",
            "| delivery_date | as_of_date | manifest_sha256 | rows_counted_sha256 |",
            "|---|---|---|---|",
        ]
    )
    for row in sorted(rows, key=lambda item: (item["delivery_date"], item["as_of_date"])):
        lines.append(f"| {row['delivery_date']} | {row['as_of_date']} | `{row['manifest_sha256']}` | `{row['rows_counted_sha256']}` |")
    lines.append("")
    return "\n".join(lines)


def _verify_report_markdown_regenerates(
    *,
    root: Path,
    markdown_path: Path,
    text: str,
    report_rows: list[dict[str, str]],
    start_date: date,
    end_date: date,
    report_date: date,
    min_delay_days: int,
) -> list[str]:
    rel = markdown_path.relative_to(root).as_posix()
    kind = markdown_path.parent.name
    if kind not in {"weekly", "monthly"}:
        return [f"report has unsupported report kind path: {rel}"]
    expected = _render_report_markdown(
        _report_summary(
            root,
            kind=kind,
            rows=report_rows,
            start_date=start_date,
            end_date=end_date,
            report_date=report_date,
            min_delay_days=min_delay_days,
        ),
        report_rows,
    )
    return [] if text == expected else [f"report markdown does not match deterministic regeneration: {rel}"]


def _markdown_match(text: str, pattern: str) -> str:
    match = re.search(pattern, text, flags=re.MULTILINE)
    return match.group(1) if match else ""


def _report_metadata(text: str) -> dict[str, date | str | None]:
    start = _markdown_match(text, r"^Period:\s*(\d{4}-\d{2}-\d{2})\s+to\s+\d{4}-\d{2}-\d{2}\s*$")
    end = _markdown_match(text, r"^Period:\s*\d{4}-\d{2}-\d{2}\s+to\s+(\d{4}-\d{2}-\d{2})\s*$")
    report = _markdown_match(text, r"^Report date:\s*(\d{4}-\d{2}-\d{2})\s*$")
    rows_hash = _markdown_match(text, r"^Rows counted SHA256:\s*`?([^`\s]+)`?\s*$")
    parsed: dict[str, date | str | None] = {
        "start_date": None,
        "end_date": None,
        "report_date": None,
        "rows_counted_sha256": rows_hash,
    }
    for key, raw in (("start_date", start), ("end_date", end), ("report_date", report)):
        if raw:
            parsed[key] = date.fromisoformat(raw)
    return parsed


def _sample_manifest_sha(text: str) -> str:
    match = re.search(r"Manifest SHA256: `([0-9a-f]{64})`", text)
    return match.group(1) if match else ""


def _correction_note_relpath(row: dict[str, str]) -> Path:
    manifest_sha = row.get("manifest_sha256") or "missing-manifest"
    return CORRECTIONS_ROOT / f"{row.get('as_of_date', 'unknown-date')}_{row.get('carrier', 'w31')}_{manifest_sha[:12]}.md"


def _verify_correction_note(root: Path, row: dict[str, str], *, line_number: int) -> list[str]:
    relpath = _correction_note_relpath(row)
    path = root / relpath
    if not path.is_file():
        return [f"daily ledger line {line_number} correction row missing public correction note: {relpath.as_posix()}"]
    text = path.read_text(encoding="utf-8")
    errors: list[str] = []
    if GENERATED_HEADER not in text:
        errors.append(f"correction note missing generated header: {relpath.as_posix()}")
    for label, value in (
        ("original manifest", row.get("correction_of_manifest_sha256", "")),
        ("correction manifest", row.get("manifest_sha256", "")),
    ):
        if value and value not in text:
            errors.append(f"correction note missing {label} sha: {relpath.as_posix()}")
    for required in ("## Cause", "## Blast Radius", "## Corrected Fields", "## Verification", "Responsible human approval:"):
        if required not in text:
            errors.append(f"correction note missing required section {required!r}: {relpath.as_posix()}")
    return errors


def _verify_pending_timestamp_input(root: Path, row: dict[str, str], *, line_number: int) -> list[str]:
    relpath = _timestamp_proof_input_relpath(row)
    if not relpath:
        return []
    path = root / relpath
    if not path.exists():
        return []
    if not path.is_file():
        return [f"pending timestamp input is not a file at line {line_number}: {relpath}"]
    expected = _timestamp_proof_input_payload(row)
    actual = path.read_text(encoding="utf-8")
    if actual != expected:
        return [f"pending timestamp input payload mismatch at line {line_number}: {relpath}"]
    return []


def _verify_opentimestamps_with_cli(root: Path, row: dict[str, str], *, line_number: int, ots_bin: str) -> list[str]:
    proof_path = row.get("opentimestamps_proof_path", "")
    if not proof_path:
        return []
    try:
        result = subprocess.run(
            [ots_bin, "verify", str(root / proof_path)],
            cwd=root,
            text=True,
            capture_output=True,
            check=False,
        )
    except FileNotFoundError:
        return [f"OpenTimestamps verifier not found for line {line_number}: {ots_bin}"]
    if result.returncode != 0:
        detail = (result.stderr or result.stdout or "OpenTimestamps verification failed").strip()
        return [f"OpenTimestamps verification failed at line {line_number}: {detail}"]
    return []


def _sha256_file(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as fh:
        for chunk in iter(lambda: fh.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def _read_base_csv_rows(
    root: Path,
    *,
    base_ref: str,
    relpath: Path,
    columns: tuple[str, ...],
) -> tuple[list[dict[str, str]], list[str]]:
    result = subprocess.run(
        ["git", "--no-optional-locks", "show", f"{base_ref}:{relpath.as_posix()}"],
        cwd=root,
        text=True,
        capture_output=True,
        check=False,
    )
    if result.returncode != 0:
        return [], []
    reader = csv.DictReader(result.stdout.splitlines())
    if tuple(reader.fieldnames or ()) != columns:
        return [], [f"base schema mismatch at {base_ref}:{relpath.as_posix()}: {reader.fieldnames}"]
    return list(reader), []


def _verify_append_only_csv(
    root: Path,
    *,
    relpath: Path,
    columns: tuple[str, ...],
    base_ref: str,
) -> list[str]:
    current_rows, current_errors = _read_csv_rows(root / relpath, columns)
    if current_errors:
        return current_errors
    base_rows, base_errors = _read_base_csv_rows(root, base_ref=base_ref, relpath=relpath, columns=columns)
    if base_errors:
        return base_errors
    if len(current_rows) < len(base_rows):
        return [f"{relpath.as_posix()} is not append-only: row count shrank {len(base_rows)} -> {len(current_rows)}"]
    for idx, prior in enumerate(base_rows):
        current = current_rows[idx]
        expected = {name: prior.get(name, "") for name in columns}
        actual = {name: current.get(name, "") for name in columns}
        if actual == expected:
            continue
        return [f"{relpath.as_posix()} is not append-only: prior row {idx + 2} was modified"]
    return []


def _verify_daily_ledger(root: Path, append_only_base_ref: str | None) -> tuple[list[dict[str, str]], list[str]]:
    rows, errors = _read_csv_rows(root / DAILY_LEDGER, LEDGER_COLUMNS)
    if append_only_base_ref:
        errors.extend(
            _verify_append_only_csv(
                root,
                relpath=DAILY_LEDGER,
                columns=LEDGER_COLUMNS,
                base_ref=append_only_base_ref,
            )
        )

    seen: set[tuple[str, str, str, str]] = set()
    prior_by_manifest: dict[str, dict[str, str]] = {}
    for idx, row in enumerate(rows, start=2):
        key = (row["as_of_date"], row["delivery_date"], row["carrier"], row["prospective_or_backfill"])
        correction_of = row["correction_of_manifest_sha256"]
        if correction_of:
            corrected = prior_by_manifest.get(correction_of)
            if corrected is None:
                errors.append(f"daily ledger line {idx} correction_of_manifest_sha256 does not reference an earlier row")
            else:
                corrected_key = (
                    corrected["as_of_date"],
                    corrected["delivery_date"],
                    corrected["carrier"],
                    corrected["prospective_or_backfill"],
                )
                if corrected_key != key:
                    errors.append(f"daily ledger line {idx} correction key does not match corrected row key")
            errors.extend(_verify_correction_note(root, row, line_number=idx))
        elif key in seen:
            errors.append(f"duplicate daily ledger key at line {idx}: {key}")
        else:
            seen.add(key)
        if row["carrier"] != "w31":
            errors.append(f"daily ledger line {idx} must use carrier=w31, got {row['carrier']!r}")
        if row["prospective_or_backfill"] != "prospective":
            errors.append(f"daily ledger line {idx} must be prospective-only")
        if not row["manifest_sha256"]:
            errors.append(f"daily ledger line {idx} missing manifest_sha256")
        if not row["methodology_version"]:
            errors.append(f"daily ledger line {idx} missing methodology_version")
        if row["valid_day_status"] == "excluded" and not row["exclusion_reason"]:
            errors.append(f"daily ledger line {idx} excluded without exclusion_reason")
        if row["valid_day_status"] == "invalid" and not (row["exclusion_reason"] or row["notes"]):
            errors.append(f"daily ledger line {idx} invalid without public reason")
        if row["timestamp_status"] not in ALLOWED_TIMESTAMP_STATUSES:
            errors.append(f"daily ledger line {idx} has unexpected timestamp_status={row['timestamp_status']!r}")
        proof_path = row["opentimestamps_proof_path"]
        if row["timestamp_status"] == "timestamp_pending" and proof_path:
            errors.append(f"daily ledger line {idx} pending timestamp row must not have proof path")
        if row["timestamp_status"] == "timestamp_pending":
            errors.extend(_verify_pending_timestamp_input(root, row, line_number=idx))
        if row["timestamp_status"] == "opentimestamps_proof":
            if not proof_path:
                errors.append(f"daily ledger line {idx} missing opentimestamps_proof_path")
            elif not proof_path.startswith("hashes/opentimestamps/"):
                errors.append(f"daily ledger line {idx} proof path must be under hashes/opentimestamps/")
        if row["timestamp_status"] == "timestamp_failed_giving_up" and proof_path:
            errors.append(f"daily ledger line {idx} failed timestamp row must not have proof path")
        if proof_path and not (root / proof_path).is_file():
            errors.append(f"daily ledger line {idx} proof path does not exist: {proof_path}")
        if row["manifest_sha256"]:
            prior_by_manifest[row["manifest_sha256"]] = row
    return rows, errors


def _verify_backfill_ledger(root: Path, append_only_base_ref: str | None) -> list[str]:
    rows, errors = _read_csv_rows(root / BACKFILL_LEDGER, LEDGER_COLUMNS)
    if append_only_base_ref:
        errors.extend(
            _verify_append_only_csv(
                root,
                relpath=BACKFILL_LEDGER,
                columns=LEDGER_COLUMNS,
                base_ref=append_only_base_ref,
            )
        )
    seen: set[tuple[str, str, str, str]] = set()
    for idx, row in enumerate(rows, start=2):
        key = (row["as_of_date"], row["delivery_date"], row["carrier"], row["prospective_or_backfill"])
        if key in seen:
            errors.append(f"duplicate backfill ledger key at line {idx}: {key}")
        seen.add(key)
        if row["carrier"] != "w31":
            errors.append(f"backfill ledger line {idx} must use carrier=w31, got {row['carrier']!r}")
        if row["prospective_or_backfill"] != "backfill":
            errors.append(f"backfill ledger line {idx} must be marked backfill")
    return errors


def _verify_outcome_summaries(
    root: Path,
    *,
    ledger_rows: list[dict[str, str]],
    append_only_base_ref: str | None,
) -> list[str]:
    path = root / OUTCOME_SUMMARIES
    if not path.exists():
        return []
    rows, errors = _read_csv_rows(path, OUTCOME_SUMMARY_COLUMNS)
    if append_only_base_ref:
        errors.extend(
            _verify_append_only_csv(
                root,
                relpath=OUTCOME_SUMMARIES,
                columns=OUTCOME_SUMMARY_COLUMNS,
                base_ref=append_only_base_ref,
            )
        )

    ledger_by_manifest = {row["manifest_sha256"]: row for row in ledger_rows if row.get("manifest_sha256")}
    seen: set[tuple[str, str, str, str]] = set()
    for idx, row in enumerate(rows, start=2):
        key = (row["as_of_date"], row["delivery_date"], row["carrier"], row["manifest_sha256"])
        if key in seen:
            errors.append(f"duplicate outcome summary key at line {idx}: {key}")
        seen.add(key)
        if row["carrier"] != "w31":
            errors.append(f"outcome summary line {idx} must use carrier=w31, got {row['carrier']!r}")
        if row["outcome_status"] != PUBLIC_OUTCOME_STATUS:
            errors.append(f"public outcome summary line {idx} must be settlement-complete, got {row['outcome_status']!r}")
        if not row["methodology_version"]:
            errors.append(f"outcome summary line {idx} missing methodology_version")
        if not row["rows_counted_sha256"]:
            errors.append(f"outcome summary line {idx} missing rows_counted_sha256")
        if not row["private_outcome_sha256"]:
            errors.append(f"outcome summary line {idx} missing private_outcome_sha256")
        if not row["ercot_data_snapshot_sha256"]:
            errors.append(f"outcome summary line {idx} missing ercot_data_snapshot_sha256")
        ledger_row = ledger_by_manifest.get(row["manifest_sha256"])
        if ledger_row is None:
            errors.append(f"outcome summary line {idx} does not reference a public ledger manifest")
        elif (
            ledger_row["as_of_date"] != row["as_of_date"]
            or ledger_row["delivery_date"] != row["delivery_date"]
            or ledger_row["carrier"] != row["carrier"]
            or ledger_row["methodology_version"] != row["methodology_version"]
        ):
            errors.append(f"outcome summary line {idx} does not match referenced ledger row")
        else:
            if ledger_row.get("prospective_or_backfill") != "prospective":
                errors.append(f"outcome summary line {idx} references non-prospective ledger row")
            if ledger_row.get("valid_day_status") != "valid":
                errors.append(f"outcome summary line {idx} references non-valid ledger row")
    return errors


def _verify_timestamp_proofs(
    root: Path,
    *,
    ledger_rows: list[dict[str, str]],
    append_only_base_ref: str | None,
    verify_opentimestamps: bool = False,
    ots_bin: str = "ots",
) -> list[str]:
    path = root / TIMESTAMP_PROOFS
    errors: list[str] = []
    if not path.exists():
        if any(row.get("timestamp_status") == "opentimestamps_proof" for row in ledger_rows):
            errors.append(f"missing timestamp proof ledger: {TIMESTAMP_PROOFS.as_posix()}")
        return errors
    rows, row_errors = _read_csv_rows(path, TIMESTAMP_PROOF_COLUMNS)
    errors.extend(row_errors)
    if row_errors:
        return errors
    if append_only_base_ref:
        errors.extend(
            _verify_append_only_csv(
                root,
                relpath=TIMESTAMP_PROOFS,
                columns=TIMESTAMP_PROOF_COLUMNS,
                base_ref=append_only_base_ref,
            )
        )
    ledger_by_manifest = {row["manifest_sha256"]: row for row in ledger_rows if row.get("manifest_sha256")}
    seen: set[str] = set()
    proof_by_manifest: dict[str, dict[str, str]] = {}
    for idx, row in enumerate(rows, start=2):
        manifest_sha = row["manifest_sha256"]
        if manifest_sha in seen:
            errors.append(f"duplicate timestamp proof row at line {idx}: {manifest_sha}")
        seen.add(manifest_sha)
        proof_by_manifest[manifest_sha] = row
        ledger_row = ledger_by_manifest.get(manifest_sha)
        if ledger_row is None:
            errors.append(f"timestamp proof line {idx} does not reference a public ledger manifest")
            continue
        if (
            ledger_row["as_of_date"] != row["as_of_date"]
            or ledger_row["delivery_date"] != row["delivery_date"]
            or ledger_row["carrier"] != row["carrier"]
        ):
            errors.append(f"timestamp proof line {idx} does not match referenced ledger row")
        if row["public_ledger_row_sha256"] != _ledger_row_sha256(ledger_row):
            errors.append(f"timestamp proof line {idx} has wrong public_ledger_row_sha256")
        if row["timestamp_status"] not in {"opentimestamps_proof", "timestamp_failed_giving_up"}:
            errors.append(f"timestamp proof line {idx} has unexpected timestamp_status={row['timestamp_status']!r}")
        proof_input_path = row["proof_input_path"]
        proof_path = row["opentimestamps_proof_path"]
        if not proof_input_path.startswith("hashes/opentimestamps/"):
            errors.append(f"timestamp proof line {idx} proof_input_path must be under hashes/opentimestamps/")
        if row["timestamp_status"] == "opentimestamps_proof":
            if not proof_path.startswith("hashes/opentimestamps/"):
                errors.append(f"timestamp proof line {idx} opentimestamps_proof_path must be under hashes/opentimestamps/")
            required_artifacts = (
                ("proof_input_path", "proof_input_sha256"),
                ("opentimestamps_proof_path", "opentimestamps_proof_sha256"),
            )
        else:
            if proof_path or row["opentimestamps_proof_sha256"]:
                errors.append(f"failed timestamp line {idx} must not have OpenTimestamps proof fields")
            if not row["notes"]:
                errors.append(f"failed timestamp line {idx} requires notes")
            required_artifacts = (("proof_input_path", "proof_input_sha256"),)
        for column, digest_column in required_artifacts:
            relpath = row[column]
            artifact = root / relpath
            if not artifact.is_file():
                errors.append(f"timestamp proof line {idx} missing artifact: {relpath}")
                continue
            if row[digest_column] != _sha256_file(artifact):
                errors.append(f"timestamp proof line {idx} {digest_column} does not match artifact")
        if verify_opentimestamps and row["timestamp_status"] == "opentimestamps_proof":
            errors.extend(_verify_opentimestamps_with_cli(root, row, line_number=idx, ots_bin=ots_bin))
    for idx, ledger_row in enumerate(ledger_rows, start=2):
        if ledger_row.get("timestamp_status") != "opentimestamps_proof":
            continue
        proof_row = proof_by_manifest.get(ledger_row["manifest_sha256"])
        if proof_row is None:
            errors.append(f"daily ledger line {idx} has proof status but no timestamp proof row")
        elif proof_row["opentimestamps_proof_path"] != ledger_row["opentimestamps_proof_path"]:
            errors.append(f"daily ledger line {idx} proof path does not match timestamp proof row")
    return errors


def _canonical_attestation_body(payload: dict[str, object]) -> bytes:
    return json.dumps(payload, sort_keys=True, separators=(",", ":"), default=str).encode("utf-8")


def _allowed_signer_identity_present(path: Path, identity: str) -> bool:
    try:
        lines = path.read_text(encoding="utf-8").splitlines()
    except FileNotFoundError:
        return False
    for raw_line in lines:
        line = raw_line.strip()
        if not line or line.startswith("#"):
            continue
        principals = line.split(None, 1)[0]
        if identity in {principal.strip() for principal in principals.split(",")}:
            return True
    return False


def _verify_ssh_attestation_signature(payload: dict[str, object], *, allowed_signers_path: Path) -> str | None:
    signature = payload.get("signature")
    public_key = str(payload.get("public_key") or "")
    identity = str(payload.get("signature_identity") or "")
    namespace = str(payload.get("signature_namespace") or "")
    if not signature or not public_key or not identity or not namespace:
        return "missing signature, public_key, signature_identity, or signature_namespace"
    if not allowed_signers_path.is_file():
        return f"allowed signers file missing: {ATTESTATION_ALLOWED_SIGNERS.as_posix()}"
    if not _allowed_signer_identity_present(allowed_signers_path, identity):
        return f"signature_identity {identity!r} is not listed in {ATTESTATION_ALLOWED_SIGNERS.as_posix()}"
    signed_payload = dict(payload)
    signed_payload.pop("signature", None)
    body = _canonical_attestation_body(signed_payload)
    with tempfile.TemporaryDirectory(prefix="track-record-attestation-verify-") as tmp_raw:
        root = Path(tmp_raw)
        signature_path = root / "attestation.sig"
        signature_path.write_text(str(signature), encoding="utf-8")
        result = subprocess.run(
            [
                "ssh-keygen",
                "-Y",
                "verify",
                "-f",
                str(allowed_signers_path),
                "-I",
                identity,
                "-n",
                namespace,
                "-s",
                str(signature_path),
            ],
            input=body,
            capture_output=True,
            check=False,
        )
    if result.returncode != 0:
        return (result.stderr or result.stdout).decode("utf-8", errors="replace").strip() or "signature verification failed"
    return None


def _verify_attestations(root: Path, ledger_rows: list[dict[str, str]]) -> list[str]:
    errors: list[str] = []
    attestation_root = root / ATTESTATION_ROOT
    if not attestation_root.exists():
        return errors
    allowed_signers_path = root / ATTESTATION_ALLOWED_SIGNERS
    ledger_by_manifest = {row["manifest_sha256"]: row for row in ledger_rows if row.get("manifest_sha256")}
    for path in sorted(attestation_root.rglob("*.json")):
        rel = path.relative_to(root).as_posix()
        try:
            payload = json.loads(path.read_text(encoding="utf-8"))
        except json.JSONDecodeError as exc:
            errors.append(f"invalid attestation json in {rel}: {exc}")
            continue
        if not isinstance(payload, dict):
            errors.append(f"attestation is not an object: {rel}")
            continue
        if payload.get("signature_algorithm") != "openssh-signature-v1":
            errors.append(f"attestation has unsupported signature_algorithm in {rel}")
        if payload.get("signature_namespace") != ATTESTATION_SIGNATURE_NAMESPACE:
            errors.append(f"attestation has unexpected signature_namespace in {rel}")
        manifest_sha256 = str(payload.get("manifest_sha256") or "")
        ledger_row = ledger_by_manifest.get(manifest_sha256)
        if ledger_row is None:
            errors.append(f"attestation does not reference a public ledger manifest: {rel}")
        else:
            expected_row_sha = _ledger_row_sha256(ledger_row)
            if payload.get("public_ledger_row_sha256") != expected_row_sha:
                errors.append(f"attestation ledger row hash mismatch in {rel}")
        signature_error = _verify_ssh_attestation_signature(payload, allowed_signers_path=allowed_signers_path)
        if signature_error:
            errors.append(f"attestation signature verification failed in {rel}: {signature_error}")
    return errors


def _verify_report_rows(root: Path, markdown_path: Path, text: str, *, min_delay_days: int) -> list[str]:
    errors: list[str] = []
    rel = markdown_path.relative_to(root).as_posix()
    csv_path = markdown_path.with_suffix(".csv")
    report_rows, row_errors = _read_csv_rows(csv_path, OUTCOME_SUMMARY_COLUMNS)
    if row_errors:
        return row_errors
    if not report_rows:
        return [f"report companion csv has no rows: {csv_path.relative_to(root).as_posix()}"]
    outcome_rows, outcome_errors = _read_csv_rows(root / OUTCOME_SUMMARIES, OUTCOME_SUMMARY_COLUMNS)
    ledger_rows, ledger_errors = _read_csv_rows(root / DAILY_LEDGER, LEDGER_COLUMNS)
    errors.extend(outcome_errors)
    errors.extend(ledger_errors)
    if outcome_errors or ledger_errors:
        return errors

    metadata = _report_metadata(text)
    for name in ("start_date", "end_date", "report_date"):
        if metadata[name] is None:
            errors.append(f"report missing parseable {name}: {rel}")
    rows_hash = str(metadata["rows_counted_sha256"] or "")
    if rows_hash and _report_rows_counted_sha256(report_rows) != rows_hash:
        errors.append(f"report rows_counted_sha256 mismatch: {rel}")

    outcome_by_key = {
        (row["as_of_date"], row["delivery_date"], row["carrier"], row["manifest_sha256"]): row
        for row in outcome_rows
    }
    ledger_by_manifest = {row["manifest_sha256"]: row for row in ledger_rows if row.get("manifest_sha256")}
    corrected_manifests = {row["correction_of_manifest_sha256"] for row in ledger_rows if row.get("correction_of_manifest_sha256")}
    methodology_versions = {row.get("methodology_version", "") for row in report_rows if row.get("methodology_version")}
    if len(methodology_versions) > 1 and "## Methodology Segments" not in text:
        errors.append(f"report spanning multiple methodology versions lacks methodology segments: {rel}")

    start_date = metadata["start_date"]
    end_date = metadata["end_date"]
    report_date = metadata["report_date"]
    latest_allowed = report_date - timedelta(days=min_delay_days) if isinstance(report_date, date) else None
    for idx, row in enumerate(report_rows, start=2):
        row_key = (row["as_of_date"], row["delivery_date"], row["carrier"], row["manifest_sha256"])
        outcome = outcome_by_key.get(row_key)
        if outcome is None:
            errors.append(f"report row {idx} does not reference a delayed outcome summary: {rel}")
        elif {name: row.get(name, "") for name in OUTCOME_SUMMARY_COLUMNS} != {name: outcome.get(name, "") for name in OUTCOME_SUMMARY_COLUMNS}:
            errors.append(f"report row {idx} differs from delayed outcome summary: {rel}")
        ledger = ledger_by_manifest.get(row["manifest_sha256"])
        if ledger is None:
            errors.append(f"report row {idx} does not reference a public ledger manifest: {rel}")
        else:
            if row["manifest_sha256"] in corrected_manifests:
                errors.append(f"report row {idx} uses superseded corrected manifest: {rel}")
            if ledger["prospective_or_backfill"] != "prospective":
                errors.append(f"report row {idx} references non-prospective ledger row: {rel}")
            if ledger["valid_day_status"] != "valid":
                errors.append(f"report row {idx} references non-valid ledger row: {rel}")
            for column in ("as_of_date", "delivery_date", "carrier", "methodology_version"):
                if ledger[column] != row[column]:
                    errors.append(f"report row {idx} {column} does not match ledger row: {rel}")
        if row["carrier"] != "w31":
            errors.append(f"report row {idx} has non-public carrier: {rel}")
        if row["outcome_status"] != "outcome_joined":
            errors.append(f"report row {idx} is not settlement-complete: {rel}")
        delivery = date.fromisoformat(row["delivery_date"])
        if isinstance(start_date, date) and isinstance(end_date, date) and not (start_date <= delivery <= end_date):
            errors.append(f"report row {idx} delivery date outside report period: {rel}")
        if latest_allowed is not None and delivery > latest_allowed:
            errors.append(f"report row {idx} is not delayed by {min_delay_days} days: {rel}")
    if isinstance(start_date, date) and isinstance(end_date, date) and isinstance(report_date, date):
        errors.extend(
            _verify_report_markdown_regenerates(
                root=root,
                markdown_path=markdown_path,
                text=text,
                report_rows=report_rows,
                start_date=start_date,
                end_date=end_date,
                report_date=report_date,
                min_delay_days=min_delay_days,
            )
        )
    return errors


def _verify_reports(root: Path, *, min_delay_days: int = 2) -> list[str]:
    errors: list[str] = []
    for report_root in (root / "reports" / "weekly", root / "reports" / "monthly"):
        if not report_root.exists():
            continue
        for markdown_path in report_root.glob("*.md"):
            if markdown_path.name == "README.md":
                continue
            rel = markdown_path.relative_to(root).as_posix()
            text = markdown_path.read_text(encoding="utf-8")
            if GENERATED_HEADER not in text:
                errors.append(f"report missing generated header: {rel}")
            if "Rows counted SHA256:" not in text:
                errors.append(f"report missing rows_counted_sha256: {rel}")
            if "Methodology versions:" not in text:
                errors.append(f"report missing methodology versions: {rel}")
            if "## Operational Discipline" not in text:
                errors.append(f"report missing operational discipline section: {rel}")
            if "## Risk/Distribution" not in text:
                errors.append(f"report missing risk/distribution section: {rel}")
            if not markdown_path.with_suffix(".csv").is_file():
                errors.append(f"report missing companion csv: {markdown_path.with_suffix('.csv').relative_to(root).as_posix()}")
            else:
                errors.extend(_verify_report_rows(root, markdown_path, text, min_delay_days=min_delay_days))
    return errors


def _verify_samples(root: Path, ledger_rows: list[dict[str, str]]) -> list[str]:
    errors: list[str] = []
    sample_root = root / PUBLIC_SAMPLE_ROOT
    if not sample_root.exists():
        return errors
    ledger_by_manifest = {row.get("manifest_sha256", ""): row for row in ledger_rows}
    for markdown_path in sorted(sample_root.glob("*.md")):
        if markdown_path.name == "README.md":
            continue
        rel = markdown_path.relative_to(root).as_posix()
        text = markdown_path.read_text(encoding="utf-8")
        if GENERATED_HEADER not in text:
            errors.append(f"sample missing generated header: {rel}")
        for marker in ("## Approval", "- Approval id:", "- Approved by:", "- Approval reason:", "## Hash References"):
            if marker not in text:
                errors.append(f"sample missing required marker {marker!r}: {rel}")
        for pattern in FORBIDDEN_CONTENT_PATTERNS:
            if pattern.search(text):
                errors.append(f"sample contains forbidden raw-signal content pattern {pattern.pattern!r}: {rel}")
                break
        manifest_sha = _sample_manifest_sha(text)
        if not manifest_sha:
            errors.append(f"sample missing manifest SHA256: {rel}")
            continue
        ledger_row = ledger_by_manifest.get(manifest_sha)
        if ledger_row is None:
            errors.append(f"sample manifest does not reference public ledger row: {rel}")
            continue
        if ledger_row.get("carrier") != "w31":
            errors.append(f"sample manifest references non-public carrier row: {rel}")
        if ledger_row.get("prospective_or_backfill") != "prospective":
            errors.append(f"sample manifest references non-prospective row: {rel}")
        if ledger_row.get("valid_day_status") != "valid":
            errors.append(f"sample manifest references non-valid-day row: {rel}")
    return errors


def _read_csv_rows_optional(path: Path, columns: tuple[str, ...]) -> list[dict[str, str]]:
    rows, errors = _read_csv_rows(path, columns)
    return [] if errors else rows


def _latest_row(rows: list[dict[str, str]]) -> dict[str, str] | None:
    if not rows:
        return None
    return sorted(rows, key=lambda row: (row.get("as_of_date", ""), row.get("delivery_date", ""), row.get("manifest_sha256", "")))[-1]


def _latest_report(root: Path, kind: str) -> str:
    report_root = root / "reports" / kind
    if not report_root.exists():
        return ""
    reports = sorted(path for path in report_root.glob("*.md") if path.name != "README.md")
    return reports[-1].relative_to(root).as_posix() if reports else ""


def _status_summary(root: Path) -> dict[str, object]:
    daily_rows = _read_csv_rows_optional(root / DAILY_LEDGER, LEDGER_COLUMNS)
    backfill_rows = _read_csv_rows_optional(root / BACKFILL_LEDGER, LEDGER_COLUMNS)
    latest = _latest_row(daily_rows)
    valid_rows = [row for row in daily_rows if row.get("valid_day_status") == "valid"]
    invalid_rows = [row for row in daily_rows if row.get("valid_day_status") == "invalid"]
    excluded_rows = [row for row in daily_rows if row.get("valid_day_status") == "excluded"]
    methodology = latest.get("methodology_version") if latest else DEFAULT_METHODOLOGY_VERSION
    return {
        "public_carrier": "W31",
        "methodology_version": methodology or DEFAULT_METHODOLOGY_VERSION,
        "prospective_rows": len(daily_rows),
        "valid_rows": len(valid_rows),
        "invalid_rows": len(invalid_rows),
        "excluded_rows": len(excluded_rows),
        "backfill_rows": len(backfill_rows),
        "latest_row": latest or {},
        "latest_weekly_report": _latest_report(root, "weekly"),
        "latest_monthly_report": _latest_report(root, "monthly"),
    }


def _render_readme(summary: dict[str, object]) -> str:
    latest = summary["latest_row"] if isinstance(summary["latest_row"], dict) else {}
    latest_text = latest.get("as_of_date", "none") if latest else "none"
    latest_hash = latest.get("manifest_sha256", "") if latest else ""
    lines = [
        GENERATED_HEADER,
        "",
        "# ERCOT PTP Track Record",
        "",
        "Public audit repository for timestamped ERCOT PTP track-record discipline.",
        "",
        "This repository publishes public proof artifacts for the current ERCOT PTP production process. "
        f"The public carrier code is {summary['public_carrier']}, an opaque audit/release identifier rather than "
        "a strategy description or model-mechanism claim. The repository is designed to prove process discipline: "
        "prospective hash publication, append-only handling, delayed aggregate reporting, correction lineage, "
        "and verification rules.",
        "",
        "This repository does not publish live trade instructions, raw scored signals, model internals, private comparator evidence, or same-day actionable advisory details.",
        "",
        "## Current Status",
        "",
        "- Public production process: active.",
        f"- Carrier code: {summary['public_carrier']} (opaque audit identifier).",
        f"- Methodology version: `{summary['methodology_version']}`.",
        f"- Prospective live rows: {summary['prospective_rows']}.",
        f"- Valid rows: {summary['valid_rows']}.",
        f"- Invalid rows: {summary['invalid_rows']}.",
        f"- Excluded rows: {summary['excluded_rows']}.",
        f"- Backfill rows: {summary['backfill_rows']}.",
        f"- Latest as-of date: {latest_text}.",
    ]
    if latest_hash:
        lines.append(f"- Latest manifest SHA256: `{latest_hash}`.")
    if summary["latest_weekly_report"]:
        lines.append(f"- Latest weekly report: `{summary['latest_weekly_report']}`.")
    if summary["latest_monthly_report"]:
        lines.append(f"- Latest monthly report: `{summary['latest_monthly_report']}`.")
    lines.extend(
        [
            "",
            "## Public Artifacts",
            "",
            "- `hashes/daily_manifest_hashes.csv`: prospective public manifest hash ledger.",
            "- `hashes/backfill_manifest_hashes.csv`: historical/backfill hash ledger, never counted in prospective reports.",
            "- `hashes/timestamp_proofs.csv`: append-only timestamp proof ledger.",
            "- `hashes/opentimestamps/`: timestamp proof inputs and OpenTimestamps proof files.",
            "- `attestations/private_manifest/`: signed attestations that a public hash matched a private manifest.",
            "- `carrier/current.md`: current public carrier status.",
            "- `carrier/operational_log.md`: public-safe automation event log.",
            "- `methodology/safety_overlay.md`: public-safe explanation of standby safety overlays.",
            "- `reports/weekly/` and `reports/monthly/`: delayed aggregate reports once enough settled outcomes exist.",
            "- `samples/delayed_advisory_examples/`: approved long-delayed examples with aggregate counts and hashes only.",
            "- `methodology/`: public rules, versioning, risk metrics, exclusions, and disclaimers.",
            "",
            "## Verification",
            "",
            "```bash",
            "python3 scripts/verify_public_repo.py .",
            "```",
            "",
            "For manual verification, start with `hashes/verification_guide.md`.",
            "",
            "## Private Boundary",
            "",
            "Full manifests, advisories, outcome joins, private baseline/research comparison evidence, canary logs, and reproducibility materials remain in the private audit vault and diligence room. Serious buyers may request that package under NDA.",
            "",
        ]
    )
    return "\n".join(lines)


def _render_current_carrier(summary: dict[str, object]) -> str:
    latest = summary["latest_row"] if isinstance(summary["latest_row"], dict) else {}
    lines = [
        GENERATED_HEADER,
        "",
        "# Current Public Process",
        "",
        f"Carrier code: {summary['public_carrier']}",
        "",
        "Status: active public carrier",
        "",
        "Meaning: opaque release/audit identifier. It is not a strategy description, model-mechanism claim, or weather-alpha claim.",
        "",
        f"Methodology version: `{summary['methodology_version']}`",
        "",
        "Public role: current prospective ERCOT PTP paper/live track-record process.",
        "",
        "Mechanism framing: topology/market-structure driven selection with a standby weather-safety gross throttle for named adverse regimes.",
        "",
        "## Public Ledger Status",
        "",
        f"- Prospective rows: {summary['prospective_rows']}",
        f"- Valid rows: {summary['valid_rows']}",
        f"- Invalid rows: {summary['invalid_rows']}",
        f"- Excluded rows: {summary['excluded_rows']}",
    ]
    if latest:
        lines.extend(
            [
                f"- Latest as-of date: {latest.get('as_of_date', '')}",
                f"- Latest delivery date: {latest.get('delivery_date', '')}",
                f"- Latest valid-day status: {latest.get('valid_day_status', '')}",
                f"- Latest timestamp status: {latest.get('timestamp_status', '')}",
                f"- Latest manifest SHA256: `{latest.get('manifest_sha256', '')}`",
            ]
        )
    lines.append("")
    return "\n".join(lines)


def _verify_status_docs(root: Path) -> list[str]:
    errors: list[str] = []
    summary = _status_summary(root)
    expected_outputs = {
        "README.md": _render_readme(summary),
        "carrier/current.md": _render_current_carrier(summary),
    }
    for relpath in ("README.md", "carrier/current.md", "carrier/operational_log.md"):
        path = root / relpath
        if not path.is_file():
            errors.append(f"missing generated public status doc: {relpath}")
            continue
        text = path.read_text(encoding="utf-8")
        if GENERATED_HEADER not in text:
            errors.append(f"public status doc missing generated header: {relpath}")
        expected = expected_outputs.get(relpath)
        if expected is not None and text != expected:
            errors.append(f"public status doc does not match deterministic regeneration: {relpath}")
        if relpath == "carrier/operational_log.md":
            for pattern in OPERATIONAL_LOG_FORBIDDEN_CONTENT_PATTERNS:
                if pattern.search(text):
                    errors.append(f"operational log contains forbidden public content pattern {pattern.pattern!r}: {relpath}")
                    break
    return errors


def _verify_privacy_boundary(root: Path) -> list[str]:
    errors: list[str] = []
    for path in root.rglob("*"):
        if not path.is_file() or ".git" in path.parts:
            continue
        rel = path.relative_to(root).as_posix()
        lowered = rel.lower()
        for pattern in FORBIDDEN_PATH_PATTERNS:
            if pattern.search(lowered):
                errors.append(f"forbidden public artifact path: {rel}")
                break
        if rel in CONTENT_SCAN_EXEMPT or path.suffix.lower() not in CONTENT_SCAN_SUFFIXES:
            continue
        try:
            text = path.read_text(encoding="utf-8")
        except UnicodeDecodeError:
            continue
        for pattern in FORBIDDEN_CONTENT_PATTERNS:
            if pattern.search(text):
                errors.append(f"forbidden raw-signal content pattern {pattern.pattern!r} in {rel}")
                break
    return errors


def verify(
    root: Path,
    *,
    append_only_base_ref: str | None = None,
    require_signed_audit_commits: bool = False,
    verify_opentimestamps: bool = False,
    ots_bin: str = "ots",
) -> list[str]:
    errors: list[str] = []
    ledger_rows, ledger_errors = _verify_daily_ledger(root, append_only_base_ref)
    errors.extend(ledger_errors)
    errors.extend(_verify_backfill_ledger(root, append_only_base_ref))
    errors.extend(_verify_outcome_summaries(root, ledger_rows=ledger_rows, append_only_base_ref=append_only_base_ref))
    errors.extend(
        _verify_timestamp_proofs(
            root,
            ledger_rows=ledger_rows,
            append_only_base_ref=append_only_base_ref,
            verify_opentimestamps=verify_opentimestamps,
            ots_bin=ots_bin,
        )
    )
    errors.extend(_verify_attestations(root, ledger_rows))
    errors.extend(_verify_reports(root))
    errors.extend(_verify_samples(root, ledger_rows))
    errors.extend(_verify_status_docs(root))
    errors.extend(
        _verify_track_record_audit_commits(
            root,
            base_ref=append_only_base_ref,
            require_signed=require_signed_audit_commits,
        )
    )
    errors.extend(_verify_privacy_boundary(root))
    return errors


def main() -> int:
    parser = argparse.ArgumentParser(description="Verify public ERCOT PTP track-record repo guardrails.")
    parser.add_argument("root", nargs="?", default=".")
    parser.add_argument(
        "--append-only-base-ref",
        default=None,
        help="Optional git ref whose public CSV rows must remain an exact prefix of current rows.",
    )
    parser.add_argument(
        "--require-signed-audit-commits",
        action="store_true",
        help="Require commits touching generated public audit artifacts to have a git signature.",
    )
    parser.add_argument(
        "--verify-opentimestamps",
        action="store_true",
        help="Run `ots verify` for published OpenTimestamps proof artifacts.",
    )
    parser.add_argument("--ots-bin", default="ots", help="OpenTimestamps CLI binary to use with --verify-opentimestamps.")
    args = parser.parse_args()
    errors = verify(
        Path(args.root).resolve(),
        append_only_base_ref=args.append_only_base_ref,
        require_signed_audit_commits=args.require_signed_audit_commits,
        verify_opentimestamps=args.verify_opentimestamps,
        ots_bin=args.ots_bin,
    )
    if errors:
        for error in errors:
            print(f"ERROR: {error}", file=sys.stderr)
        return 1
    print("VERIFY_OK public_track_record")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
